version: '3'
services:
  database:
    image: 'mysql:5.7'
    restart: always
    ports:
      - 13311:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=invoice_service_db
